import catan.action.build_road
import catan.action.build_settlement
import catan.action.earn_resource
import catan.action.end_game
import catan.action.end_trading
import catan.action.end_turn
import catan.action.roll_dice
import catan.action.spectate
import catan.action.trade_with_environment